version: '3.1'
services:
  db-mysql-cliente:
    hostname: mysql-api-cliente
    container_name: mysql-api-cliente
    networks:
      - net
    logging:
      driver: json-file
      options:
        max-size: 500m
    image: 'mysql:8.0.21'
    environment:
      MYSQL_DATABASE: api-cliente
      MYSQL_USER: api-cliente
      MYSQL_PASSWORD: api-cliente
      MYSQL_ROOT_PASSWORD: api-cliente
    ports:
      - '3306:3306'
    expose:
      - '3306'
  redis:
    image: 'redis:5.0.3'
    container_name: redis-cache
    networks:
      - net
    ports:
      - '6379:6379'
    expose:
      - '6379'
    volumes:
      - './redis:/usr/local/etc/redis'
networks:
  net:
    driver: bridge