info:
    app:
        description: 'API de clientes da builder'
        encoding: 'UTF-8'
        java:
            version: '15'
        name: 'api-builder-cliente'
        version: '1.0-SNAPSHOT'
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 8080
spring:
    boot:
        admin:
            client:
                url: http://localhost:8080
    datasource:
        platform: ${DATABASE:mysql}
        driverClassName: ${DB_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
        url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/api-cliente?allowPublicKeyRetrieval=true&useSSL=false}
        username: ${DB_USERNAME:api-cliente}
        password: ${DB_PASSWORD:api-cliente}
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          maximum-pool-size: ${HIKARI_MAXIMUM_POOL_SIZE:40}
          minimum-idle: ${HIKARI_MINIMUM_IDLE:5}
          connection-timeout: ${HIKARI_TIMEOUT:5000}
    jpa:
        hibernate:
            ddl-auto: update
            generate-ddl: true
            show-sql: true
redis:
  root-key: ${REDIS_ROOT_KEY:cliente}
  publicKeySwapTime: ${REDIS_PUBLIC_KEY_SWAP_TIME:60} # in seconds
  ttl:
    default: ${REDIS_DEFAULT_TTL:60} # in minutes
    
caffeine:
  maximumSize:
    default: ${CAFFEINE_DEFAULT_MAX_SIZE:100}
  ttl:
    default: ${CAFFEINE_DEFAULT_TTL:60} # in minutes
    
builder:
    jwt:
        expiration: 86400000
        secret: A+X;fTJP&Pd,TD9dwVq(hsHX,ya^<wsD_UK7L+@=S;{'CydP]{v@}G'b>et;yz$*yL5S8EJN:%P:X%H9>#nYLrX}@s?CQcpspH,2emzBc!Q[V'AYa~uzF8WR~AUrMzxp/V$9([S9X#zj/CH('#]B_Hc+%fGhe27YB;^j4Xk=Ju"Ap~_&<L;=!Z;!,2UP;!hF3P]j85#*`&T]/kB/W^6$v~u6qpejL>kY^f)sy4:qTq_Ec!-z!@aAp~sLKGU>$
    origin-permitida:
        domain: http://www.builder.api-cliente.com.br
